config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'omniauth_callbacks/twitter'
  # Sign up, sign in
  controller :users do
    get 'signup' => :new
    get 'users' => :index
    post 'users' => :create
  end
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # Callbacks
  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'
  get '/auth/facebook/callback', to: 'omniauth_callbacks#facebook'

  resources :twitter_accounts
  resources :facebook_accounts do
    collection do
      get 'refresh_pages'
    end
  end
  resources :posts

  root 'home#index'
end

app/models/facebook_account.rb
class FacebookAccount
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :email, type: String
  field :image, type: String
  field :token, type: String
  field :token_expires_at, type: Time

  belongs_to :user
  has_many :facebook_pages, dependent: :destroy

  validates :email, uniqueness: true

  def client
    @client = Koala::Facebook::API.new(token)
  end

  def pages
    @pages = client.get_object("me/accounts")
  end

  def set_pages
    current_pages = facebook_pages.all
    current_pages.each do |cpage|
      page = pages.find { |page| page["id"].eql? cpage.page_id }
      unless page
        cpage.delete
      end
    end

    pages.each do |page|
      facebook_page = facebook_pages.where(page_id: page["id"]).first_or_initialize
      facebook_page.update({
        page_id: page["id"],
        name: page["name"],
        token: page["access_token"],
        category: page["category"]
      })
    end
  end
end

app/controllers/facebook_accounts_controller.rb
class FacebookAccountsController < ApplicationController
  before_action :set_facebook_account, only: [:show, :destroy]

  def index
    @facebook_accounts = Current.user.facebook_accounts
  end

  def refresh_pages
    @facebook_accounts = Current.user.facebook_accounts
    if @facebook_accounts
      @facebook_accounts.each(&:set_pages)
      notice = 'Successfully updated Facebook Pages'
    end
    redirect_to facebook_accounts_url, notice: notice || 'Unable to refresh Facebook Pages'
  end

  def destroy
    if (@facebook_account)
      notice = @facebook_account.destroy ? "Successfully disconnected #{@facebook_account.email}" : 'Something was wrong, unable to disconnect facebook account'
    end
    redirect_to facebook_accounts_url, notice: notice || 'Facebook account not found'
  end

  private
    def set_facebook_account
      @facebook_account = Current.user.facebook_accounts.find_by(id: params[:id])
    end
end

app/views/facebook_accounts/index.html.haml
.d-flex.align-items-center.justify-content-between.my-4
  %h1 Facebook Accounts

  = button_to 'auth/facebook', method: :post, class: 'btn btn-primary' do
    %i.bi.bi-facebook.icon_mr
    Connect new account
  = button_to refresh_pages_facebook_accounts_url, method: :get, class: 'btn btn-success' do
    %i.bi.bi-facebook.icon_mr
    Refresh Pages

- @facebook_accounts.each do |acc|
  .card.mb-4
    .card-body.d-flex.align-items-center
      = image_tag acc.image, class: 'rounded-circle me-4'
      .flex-fill
        %b= acc.name
        .small= acc.email
      = button_to 'Disconnect', acc, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger flex-fill'