config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'omniauth_callbacks/twitter'
  # Sign up, sign in
  controller :users do
    get 'signup' => :new
    get 'users' => :index
    post 'users' => :create
  end
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # Callbacks
  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'
  get '/auth/facebook/callback', to: 'omniauth_callbacks#facebook'

  resources :twitter_accounts
  resources :facebook_accounts do
    collection do
      get 'refresh_pages'
    end
  end
  resources :posts

  root 'home#index'
end

app/views/shared/_flash.html.haml
- if flash[:notice]
  .alert.alert-info.mt-4{role: 'alert'}
    = flash[:notice]

- if flash[:alert]
  .alert.alert-warning.mt-4{role: 'alert'}
    = flash[:alert]

app/views/shared/_form_errors.html.haml
- if form.object.errors.any?
  .alert.alert-danger
    - form.object.errors.full_messages.each do |message|
      .error_msg= message

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container.w-100
    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav
        %li.nav-item= link_to 'Home', root_path, class: 'nav-link active'
        - if Current.user
          %li.nav-item= link_to 'Posts', posts_path, class: 'nav-link'
          %li.nav-item= link_to 'Twitter Accounts', twitter_accounts_path, class: 'nav-link'
          %li.nav-item= link_to 'Facebook Accounts', facebook_accounts_path, class: 'nav-link'
    .d-flex.dropdown
      - if Current.user
        %a.nav-link.dropdown-toggle.text-light.d-flex.align-items-center{href: '', id: 'navbarDropdown', role: 'button', 'data-bs-toggle': 'dropdown', 'aria-expanded': 'false', 'data-bs-display': 'static'}
          = image_tag 'profile/default.png', size: 30, class: 'rounded-circle mx-1'
          .username.mx-1= Current.user.username
        %ul.dropdown-menu.dropdown-menu-dark.dropdown-menu-end{'aria-labelledby': 'navbarDropdown'}
          %li.dropdown-item.text-center= link_to 'Logout', logout_path, method: :delete, class: 'text-light text-decoration-none'
      - else
        %ul.navbar-nav
          %li.nav-item= link_to 'Login', login_path, class: 'nav-link'
          %li.nav-item= link_to 'Signup', signup_path, class: 'nav-link'

app/views/shared/_new_account_btns.html.haml
= button_to 'auth/twitter', method: :post, class: 'btn btn-primary mx-2' do
  %i.bi.bi-twitter.icon_mr
  Connect a new account
= button_to 'auth/facebook', method: :post, class: 'btn btn-primary mx-2' do
  %i.bi.bi-facebook.icon_mr
  Connect a new account