config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'omniauth_callbacks/twitter'
  # Sign up, sign in
  controller :users do
    get 'signup' => :new
    get 'users' => :index
    post 'users' => :create
  end
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # Callbacks
  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'
  get '/auth/facebook/callback', to: 'omniauth_callbacks#facebook'

  resources :twitter_accounts
  resources :facebook_accounts do
    collection do
      get 'refresh_pages'
    end
  end
  resources :posts

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_counter.html.haml
.counter.col-md-3.col-sm-12
  .left
    %h3
      %span.count= counter
    %p.counter-name= counter_name
  .right
    %i.bi{ class: icon }

app/views/home/_counters.html.haml
-# Provisional, tal vez crear un controlador counter?
.counters
  = render 'counter', counter: scheduled_posts.count, counter_name: 'Scheduled Posts', icon: 'bi-calendar-check-fill'
  = render 'counter', counter: Current.user.posts.count, counter_name: 'Total Posts', icon: 'bi-file-earmark-richtext-fill'
  = render 'counter', counter: Current.user.total_accounts, counter_name: 'Accounts', icon: 'bi-person-fill'

app/views/home/_dashboard.html.haml
.container-user.mt-4
  .row
    .col
      %h3.text-center= "Welcome back, <b>#{Current.user.username}</b>!".html_safe
  .row
    .col
      .btns.d-flex.justify-content-center
        - if Current.user.has_any_account?
          = link_to new_post_url, class: 'btn btn-success mx-2 text-white new_post_btn' do
            %i.bi.bi-pencil-square.icon_mr
            Schedule a Post
        = render 'shared/new_account_btns'
  .row
    .col
      = render 'counters'
      
  - if Current.user.posts.any?
    .row.my-5.posts-summary
      .col-lg-6.col-sm-12
        %h2 UPCOMING
        = render scheduled_posts.limit(5)
      .col-lg-6.col-sm-12
        %h2 LATESTS
        = render published_posts.limit(5)

app/views/home/_guest.html.haml
.bg-white.p-5.rounded-lg.m-3
  %h1.mb-2 Schedule Post App
  %h4 This is an app where you can create your posts for social networks and schedule them for when you want.
  %hr.my-4
  %p
    %b Sign up and start scheduling your posts
  .btns
    = link_to 'Sign Up', signup_path, class: 'btn btn-primary mr-3'
    = link_to 'Login', login_path, class: 'btn btn-primary'

app/views/home/index.html.haml
= render Current.user ? 'dashboard' : 'guest'